import { Noto_Sans } from "next/font/google";
import { Raleway } from "next/font/google";
import "../globals.css";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  weight: "300",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  weight: "300",
  subsets: ["latin"],
})

export const metadata = {
  title: "DriveFast",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html   
      lang="pt-br"
      className={` ${notoSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
